
#+title: security_settings on a server
#+STARTUP: showall

* conditions
In terms of security one should undestand some basic principles in order to secure the system. There is no such thing as a 100 % secure system. Some principles are common for local as well as network systems some are specific. We will focus on what to do on a linux based server in order to harden the security on them.

** multilayer
According to the OSI model there are 7 layers of IT -Security that also consist of several sublayers. This should provide you with a basic understanding of all layers without going into much detail of either one of those. As we are focusing on providing rudimentary security for your server that is also well usable for amateur users.

*1. Human*

*2. Perimeter*
   
*3. Network*
   
*4. End Point*
   
*5. Application*
   
*6. Data*
   
*7. Mission Critical Assets*

** least privilege
** keep it simple

* prerequisite
** update
** unattended upgrades
** user
** hostname
* firewall
* fail2ban
* ssh

